config/routes.rb
Rails.application.routes.draw do
  resources :inventories
  resources :markets
  resources :items
  resources :users
  get '/login',to: 'home#login'
  
  get '/main',to:  'home#main'
  get '/profile',to: 'home#profile'
  get '/change_password',to: 'home#change_password'
  get '/home/logout'
  get '/my_market',to: 'home#my_market'
  get '/purchase_history',to: 'home#purchase_history'
  get '/my_inventory',to: 'home#my_inventory'
  get '/addItem',to: 'home#addItem'
  get '/sale_history',to:'home#sale_history'
  get '/top_seller',to:'home#top_seller'
  get '/home/register'
  get '/verify_buy' ,to: 'home#verify_buy'
  get '/addStock',to:'home#addStock'
  get '/reduceStock',to:'home#reduceStock'
  post '/home/verify_change_password'
  get '/buy_item' ,to:'home#buy_item'
 post '/home/check_user'
 post '/my_market',to: 'home#my_market'
 post '/verify_buy' ,to: 'home#verify_buy'
 post '/home/verify_add_stock'
 post '/home/verify_reduce_stock'
 post '/home/deleteItem'
 post '/addStock',to:'home#addStock'
 post '/reduceStock',to:'home#reduceStock'
 post '/addItem',to: 'home#addItem'
 post '/home/verify_addItem'
 post '/top_seller',to:'home#top_seller'
 post '/home/verify_top_seller'
 post '/home/register'
 post '/buy_item' ,to:'home#buy_item'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/market.rb
class Market < ApplicationRecord
  belongs_to :user
  belongs_to :item
  self.locking_column= :lock_version
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_market, only: %i[ show edit update destroy ]

  # GET /markets or /markets.json
  def index
    @markets = Market.all
  end

  # GET /markets/1 or /markets/1.json
  def show
  end

  # GET /markets/new
  def new
    @market = Market.new
  end

  # GET /markets/1/edit
  def edit
  end

  # POST /markets or /markets.json
  def create
    @market = Market.new(market_params)

    respond_to do |format|
      if @market.save
        format.html { redirect_to market_url(@market), notice: "Market was successfully created." }
        format.json { render :show, status: :created, location: @market }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markets/1 or /markets/1.json
  def update
    respond_to do |format|
      if @market.update(market_params)
        format.html { redirect_to market_url(@market), notice: "Market was successfully updated." }
        format.json { render :show, status: :ok, location: @market }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markets/1 or /markets/1.json
  def destroy
    @market.destroy

    respond_to do |format|
      format.html { redirect_to markets_url, notice: "Market was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market
      @market = Market.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def market_params
      params.require(:market).permit(:user_id, :item_id, :price, :stock)
    end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_form.html.erb
<%= form_with(model: market) do |form| %>
  <% if market.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(market.errors.count, "error") %> prohibited this market from being saved:</h2>

      <ul>
        <% market.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :item_id, style: "display: block" %>
    <%= form.text_field :item_id %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/markets/_market.html.erb
<div id="<%= dom_id market %>">
  <p>
    <strong>User:</strong>
    <%= market.user_id %>
  </p>

  <p>
    <strong>Item:</strong>
    <%= market.item_id %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= market.price %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= market.stock %>
  </p>

</div>

app/views/markets/edit.html.erb
<h1>Editing market</h1>

<%= render "form", market: @market %>

<br>

<div>
  <%= link_to "Show this market", @market %> |
  <%= link_to "Back to markets", markets_path %>
</div>

app/views/markets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Markets</h1>

<div id="markets">
  <% @markets.each do |market| %>
    <%= render market %>
    <p>
      <%= link_to "Show this market", market %>
    </p>
  <% end %>
</div>

<%= link_to "New market", new_market_path %>

app/views/markets/new.html.erb
<h1>New market</h1>

<%= render "form", market: @market %>

<br>

<div>
  <%= link_to "Back to markets", markets_path %>
</div>

app/views/markets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @market %>

<div>
  <%= link_to "Edit this market", edit_market_path(@market) %> |
  <%= link_to "Back to markets", markets_path %>

  <%= button_to "Destroy this market", @market, method: :delete %>
</div>